//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GearLockSecurityCenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GearLockSecurityCenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;desktop.ini&quot;:true,&quot;\\NTUSER.DAT&quot;:true,&quot;\\ntuser.dat.LOG1&quot;:true,&quot;\\ntuser.dat.LOG2&quot;:true,&quot;\\NTUSER.DAT{016888bd-6c6f-11de-8d1d-001e0bcde3ec}.TM.blf&quot;:true,&quot;\\NTUSER.DAT{016888bd-6c6f-11de-8d1d-001e0bcde3ec}.TMContainer00000000000000000001.regtrans-ms&quot;:true,&quot;\\NTUSER.DAT{016888bd-6c6f-11de-8d1d-001e0bcde3ec}.TMContainer00000000000000000002.regtrans-ms&quot;:true,&quot;\\AppData\\Local\\GDIPFONTCACHEV1.DAT&quot;:true,&quot;\\AppData\\Local\\IconCache.db&quot;:true,&quot;\\AppData\\Local\\Adobe\\AAMUpdater\\1.0\\aamul.log&quot;:true,&quot;\\AppData\\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IgnoreFileJSON {
            get {
                return ResourceManager.GetString("IgnoreFileJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;\\Microsoft\\Assistance\\Client\\1.0\\en-US\\Help_CValidator.H1D&quot;:true,&quot;\\Microsoft\\Assistance\\Client\\1.0\\en-US\\Help_MKWD_AssetId.H1W&quot;:true,&quot;\\Microsoft\\Assistance\\Client\\1.0\\en-US\\Help_MKWD_BestBet.H1W&quot;:true,&quot;\\Microsoft\\Assistance\\Client\\1.0\\en-US\\Help_MTOC_help.H1H&quot;:true,&quot;\\Microsoft\\Assistance\\Client\\1.0\\en-US\\Help_MValidator.H1D&quot;:true,&quot;\\Microsoft\\Assistance\\Client\\1.0\\en-US\\Help_MValidator.Lck&quot;:true,&quot;\\Microsoft\\Assistance\\Client\\1.0\\en-US\\Help{9DAA54E8-CD95-4107-8E7F-BA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IgnoreFileJSONAllUsers {
            get {
                return ResourceManager.GetString("IgnoreFileJSONAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;\\Libraries\\RecordedTV.library-ms&quot;:true,&quot;\\Music\\Sample Music\\AlbumArtSmall.jpg&quot;:true,&quot;\\Music\\Sample Music\\AlbumArt_{0FB86398-F1BF-4F18-845A-71926CEAFFB2}_Large.jpg&quot;:true,&quot;\\Music\\Sample Music\\AlbumArt_{0FB86398-F1BF-4F18-845A-71926CEAFFB2}_Small.jpg&quot;:true,&quot;\\Music\\Sample Music\\AlbumArt_{5FA05D35-A682-4AF6-96F7-0773E42D4D16}_Large.jpg&quot;:true,&quot;\\Music\\Sample Music\\AlbumArt_{5FA05D35-A682-4AF6-96F7-0773E42D4D16}_Small.jpg&quot;:true,&quot;\\Music\\Sample Music\\Folder.jpg&quot;:true,&quot;\\Music\\Sample Music\\Kalim [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IgnoreFileJSONDefaultUser {
            get {
                return ResourceManager.GetString("IgnoreFileJSONDefaultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;\\Microsoft\\Search\\Data\\Applications\\Windows\\MSS00002.log&quot;:true,&quot;\\Microsoft\\Search\\Data\\Applications\\Windows\\GatherLogs\\SystemIndex\\SystemIndex.1.gthr&quot;:true,&quot;\\Microsoft\\Search\\Data\\Applications\\Windows\\GatherLogs\\SystemIndex\\SystemIndex.2.gthr&quot;:true,&quot;\\Microsoft\\Search\\Data\\Applications\\Windows\\Projects\\SystemIndex\\Indexer\\CiFiles\\00010003.wsb&quot;:true,&quot;\\Microsoft\\Windows\\Start Menu\\Programs\\Accessories\\Bluetooth File Transfer Wizard.lnk&quot;:true,&quot;\\Microsoft\\Windows\\WER\\Re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IgnoreFileJSONMISC1 {
            get {
                return ResourceManager.GetString("IgnoreFileJSONMISC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon KeyICON {
            get {
                object obj = ResourceManager.GetObject("KeyICON", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
